// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: signals.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_BUY               Direction = 1
	Direction_SELL              Direction = 2
	Direction_SHORT             Direction = 3
	Direction_COVER             Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNKNOWN",
		1: "BUY",
		2: "SELL",
		3: "SHORT",
		4: "COVER",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNKNOWN": 0,
		"BUY":               1,
		"SELL":              2,
		"SHORT":             3,
		"COVER":             4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_signals_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_signals_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_PENDING  OrderStatus = 0 // Staged, awaiting Green Light
	OrderStatus_APPROVED OrderStatus = 1 // Green Light given, submitted to IBKR
	OrderStatus_REJECTED OrderStatus = 2 // Trader rejected the signal
	OrderStatus_EXECUTED OrderStatus = 3 // IBKR confirmed execution
	OrderStatus_FAILED   OrderStatus = 4 // IBKR returned an error
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "REJECTED",
		3: "EXECUTED",
		4: "FAILED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"REJECTED": 2,
		"EXECUTED": 3,
		"FAILED":   4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_signals_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_signals_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{1}
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"` // UUID generated by the brain
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                     // e.g. "AAPL", "SPY"
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=marketflow.Direction" json:"direction,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                           // Number of shares / contracts
	LimitPrice    float64                `protobuf:"fixed64,5,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`     // 0 = market order
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // 0.0–1.0 from the agent debate
	Reasoning     string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                           // Human-readable explanation from agents
	StrategyName  string                 `protobuf:"bytes,8,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"` // Which alpha strategy triggered this
	ModelUsed     string                 `protobuf:"bytes,9,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`          // "ollama/qwen2.5-coder" or "bedrock/claude-3.5-sonnet"
	GeneratedAt   int64                  `protobuf:"varint,10,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`  // Unix timestamp (ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_signals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *SignalRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SignalRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *SignalRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SignalRequest) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *SignalRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SignalRequest) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *SignalRequest) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *SignalRequest) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *SignalRequest) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // true if staged successfully
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`    // Error message if not accepted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_signals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *SignalResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"` // Watch a specific signal, or empty for all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_signals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRequest) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

type SignalStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=marketflow.OrderStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalStatusUpdate) Reset() {
	*x = SignalStatusUpdate{}
	mi := &file_signals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalStatusUpdate) ProtoMessage() {}

func (x *SignalStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalStatusUpdate.ProtoReflect.Descriptor instead.
func (*SignalStatusUpdate) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{3}
}

func (x *SignalStatusUpdate) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *SignalStatusUpdate) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *SignalStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignalStatusUpdate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GreenLightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	TraderComment string                 `protobuf:"bytes,2,opt,name=trader_comment,json=traderComment,proto3" json:"trader_comment,omitempty"` // Optional note from the trader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenLightRequest) Reset() {
	*x = GreenLightRequest{}
	mi := &file_signals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenLightRequest) ProtoMessage() {}

func (x *GreenLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenLightRequest.ProtoReflect.Descriptor instead.
func (*GreenLightRequest) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{4}
}

func (x *GreenLightRequest) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *GreenLightRequest) GetTraderComment() string {
	if x != nil {
		return x.TraderComment
	}
	return ""
}

type GreenLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenLightResponse) Reset() {
	*x = GreenLightResponse{}
	mi := &file_signals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenLightResponse) ProtoMessage() {}

func (x *GreenLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenLightResponse.ProtoReflect.Descriptor instead.
func (*GreenLightResponse) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{5}
}

func (x *GreenLightResponse) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *GreenLightResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GreenLightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Max results (default 50)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRequest) Reset() {
	*x = ListPendingRequest{}
	mi := &file_signals_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRequest) ProtoMessage() {}

func (x *ListPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRequest.ProtoReflect.Descriptor instead.
func (*ListPendingRequest) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{6}
}

func (x *ListPendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPendingRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*StagedOrder         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingResponse) Reset() {
	*x = ListPendingResponse{}
	mi := &file_signals_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingResponse) ProtoMessage() {}

func (x *ListPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingResponse.ProtoReflect.Descriptor instead.
func (*ListPendingResponse) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{7}
}

func (x *ListPendingResponse) GetOrders() []*StagedOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListPendingResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StagedOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=marketflow.Direction" json:"direction,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LimitPrice    float64                `protobuf:"fixed64,5,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning     string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	StrategyName  string                 `protobuf:"bytes,8,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	Status        OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=marketflow.OrderStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedOrder) Reset() {
	*x = StagedOrder{}
	mi := &file_signals_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedOrder) ProtoMessage() {}

func (x *StagedOrder) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedOrder.ProtoReflect.Descriptor instead.
func (*StagedOrder) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{8}
}

func (x *StagedOrder) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *StagedOrder) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StagedOrder) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *StagedOrder) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StagedOrder) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *StagedOrder) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StagedOrder) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *StagedOrder) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *StagedOrder) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *StagedOrder) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_signals_proto protoreflect.FileDescriptor

const file_signals_proto_rawDesc = "" +
	"\n" +
	"\rsignals.proto\x12\n" +
	"marketflow\"\xdb\x02\n" +
	"\rSignalRequest\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x123\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x15.marketflow.DirectionR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\x05 \x01(\x01R\n" +
	"limitPrice\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12#\n" +
	"\rstrategy_name\x18\b \x01(\tR\fstrategyName\x12\x1d\n" +
	"\n" +
	"model_used\x18\t \x01(\tR\tmodelUsed\x12!\n" +
	"\fgenerated_at\x18\n" +
	" \x01(\x03R\vgeneratedAt\"c\n" +
	"\x0eSignalResponse\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"+\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\"\x9b\x01\n" +
	"\x12SignalStatusUpdate\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.marketflow.OrderStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"W\n" +
	"\x11GreenLightRequest\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12%\n" +
	"\x0etrader_comment\x18\x02 \x01(\tR\rtraderComment\"e\n" +
	"\x12GreenLightResponse\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"B\n" +
	"\x12ListPendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\\\n" +
	"\x13ListPendingResponse\x12/\n" +
	"\x06orders\x18\x01 \x03(\v2\x17.marketflow.StagedOrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe7\x02\n" +
	"\vStagedOrder\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x123\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x15.marketflow.DirectionR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\x05 \x01(\x01R\n" +
	"limitPrice\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12#\n" +
	"\rstrategy_name\x18\b \x01(\tR\fstrategyName\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.marketflow.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt*K\n" +
	"\tDirection\x12\x15\n" +
	"\x11DIRECTION_UNKNOWN\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02\x12\t\n" +
	"\x05SHORT\x10\x03\x12\t\n" +
	"\x05COVER\x10\x04*P\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\f\n" +
	"\bEXECUTED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xa7\x01\n" +
	"\rSignalService\x12E\n" +
	"\fSubmitSignal\x12\x19.marketflow.SignalRequest\x1a\x1a.marketflow.SignalResponse\x12O\n" +
	"\x11WatchSignalStatus\x12\x18.marketflow.WatchRequest\x1a\x1e.marketflow.SignalStatusUpdate0\x012\xf6\x01\n" +
	"\x11GreenLightService\x12H\n" +
	"\aApprove\x12\x1d.marketflow.GreenLightRequest\x1a\x1e.marketflow.GreenLightResponse\x12G\n" +
	"\x06Reject\x12\x1d.marketflow.GreenLightRequest\x1a\x1e.marketflow.GreenLightResponse\x12N\n" +
	"\vListPending\x12\x1e.marketflow.ListPendingRequest\x1a\x1f.marketflow.ListPendingResponseB+Z)github.com/marketflow/backend/proto;protob\x06proto3"

var (
	file_signals_proto_rawDescOnce sync.Once
	file_signals_proto_rawDescData []byte
)

func file_signals_proto_rawDescGZIP() []byte {
	file_signals_proto_rawDescOnce.Do(func() {
		file_signals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signals_proto_rawDesc), len(file_signals_proto_rawDesc)))
	})
	return file_signals_proto_rawDescData
}

var file_signals_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_signals_proto_goTypes = []any{
	(Direction)(0),              // 0: marketflow.Direction
	(OrderStatus)(0),            // 1: marketflow.OrderStatus
	(*SignalRequest)(nil),       // 2: marketflow.SignalRequest
	(*SignalResponse)(nil),      // 3: marketflow.SignalResponse
	(*WatchRequest)(nil),        // 4: marketflow.WatchRequest
	(*SignalStatusUpdate)(nil),  // 5: marketflow.SignalStatusUpdate
	(*GreenLightRequest)(nil),   // 6: marketflow.GreenLightRequest
	(*GreenLightResponse)(nil),  // 7: marketflow.GreenLightResponse
	(*ListPendingRequest)(nil),  // 8: marketflow.ListPendingRequest
	(*ListPendingResponse)(nil), // 9: marketflow.ListPendingResponse
	(*StagedOrder)(nil),         // 10: marketflow.StagedOrder
}
var file_signals_proto_depIdxs = []int32{
	0,  // 0: marketflow.SignalRequest.direction:type_name -> marketflow.Direction
	1,  // 1: marketflow.SignalStatusUpdate.status:type_name -> marketflow.OrderStatus
	10, // 2: marketflow.ListPendingResponse.orders:type_name -> marketflow.StagedOrder
	0,  // 3: marketflow.StagedOrder.direction:type_name -> marketflow.Direction
	1,  // 4: marketflow.StagedOrder.status:type_name -> marketflow.OrderStatus
	2,  // 5: marketflow.SignalService.SubmitSignal:input_type -> marketflow.SignalRequest
	4,  // 6: marketflow.SignalService.WatchSignalStatus:input_type -> marketflow.WatchRequest
	6,  // 7: marketflow.GreenLightService.Approve:input_type -> marketflow.GreenLightRequest
	6,  // 8: marketflow.GreenLightService.Reject:input_type -> marketflow.GreenLightRequest
	8,  // 9: marketflow.GreenLightService.ListPending:input_type -> marketflow.ListPendingRequest
	3,  // 10: marketflow.SignalService.SubmitSignal:output_type -> marketflow.SignalResponse
	5,  // 11: marketflow.SignalService.WatchSignalStatus:output_type -> marketflow.SignalStatusUpdate
	7,  // 12: marketflow.GreenLightService.Approve:output_type -> marketflow.GreenLightResponse
	7,  // 13: marketflow.GreenLightService.Reject:output_type -> marketflow.GreenLightResponse
	9,  // 14: marketflow.GreenLightService.ListPending:output_type -> marketflow.ListPendingResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_signals_proto_init() }
func file_signals_proto_init() {
	if File_signals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signals_proto_rawDesc), len(file_signals_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_signals_proto_goTypes,
		DependencyIndexes: file_signals_proto_depIdxs,
		EnumInfos:         file_signals_proto_enumTypes,
		MessageInfos:      file_signals_proto_msgTypes,
	}.Build()
	File_signals_proto = out.File
	file_signals_proto_goTypes = nil
	file_signals_proto_depIdxs = nil
}
