// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: signals.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalService_SubmitSignal_FullMethodName      = "/marketflow.SignalService/SubmitSignal"
	SignalService_WatchSignalStatus_FullMethodName = "/marketflow.SignalService/WatchSignalStatus"
)

// SignalServiceClient is the client API for SignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalServiceClient interface {
	// Push a new trading signal from the AI brain to the Go backend.
	SubmitSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// Stream signal status updates back to the brain (optional feedback loop).
	WatchSignalStatus(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalStatusUpdate], error)
}

type signalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalServiceClient(cc grpc.ClientConnInterface) SignalServiceClient {
	return &signalServiceClient{cc}
}

func (c *signalServiceClient) SubmitSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, SignalService_SubmitSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalServiceClient) WatchSignalStatus(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalService_ServiceDesc.Streams[0], SignalService_WatchSignalStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, SignalStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_WatchSignalStatusClient = grpc.ServerStreamingClient[SignalStatusUpdate]

// SignalServiceServer is the server API for SignalService service.
// All implementations must embed UnimplementedSignalServiceServer
// for forward compatibility.
type SignalServiceServer interface {
	// Push a new trading signal from the AI brain to the Go backend.
	SubmitSignal(context.Context, *SignalRequest) (*SignalResponse, error)
	// Stream signal status updates back to the brain (optional feedback loop).
	WatchSignalStatus(*WatchRequest, grpc.ServerStreamingServer[SignalStatusUpdate]) error
	mustEmbedUnimplementedSignalServiceServer()
}

// UnimplementedSignalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalServiceServer struct{}

func (UnimplementedSignalServiceServer) SubmitSignal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSignal not implemented")
}
func (UnimplementedSignalServiceServer) WatchSignalStatus(*WatchRequest, grpc.ServerStreamingServer[SignalStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchSignalStatus not implemented")
}
func (UnimplementedSignalServiceServer) mustEmbedUnimplementedSignalServiceServer() {}
func (UnimplementedSignalServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServiceServer will
// result in compilation errors.
type UnsafeSignalServiceServer interface {
	mustEmbedUnimplementedSignalServiceServer()
}

func RegisterSignalServiceServer(s grpc.ServiceRegistrar, srv SignalServiceServer) {
	// If the following call panics, it indicates UnimplementedSignalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalService_ServiceDesc, srv)
}

func _SignalService_SubmitSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServiceServer).SubmitSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignalService_SubmitSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServiceServer).SubmitSignal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalService_WatchSignalStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignalServiceServer).WatchSignalStatus(m, &grpc.GenericServerStream[WatchRequest, SignalStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_WatchSignalStatusServer = grpc.ServerStreamingServer[SignalStatusUpdate]

// SignalService_ServiceDesc is the grpc.ServiceDesc for SignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketflow.SignalService",
	HandlerType: (*SignalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSignal",
			Handler:    _SignalService_SubmitSignal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSignalStatus",
			Handler:       _SignalService_WatchSignalStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "signals.proto",
}

const (
	GreenLightService_Approve_FullMethodName     = "/marketflow.GreenLightService/Approve"
	GreenLightService_Reject_FullMethodName      = "/marketflow.GreenLightService/Reject"
	GreenLightService_ListPending_FullMethodName = "/marketflow.GreenLightService/ListPending"
)

// GreenLightServiceClient is the client API for GreenLightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─── Green Light Service (Dashboard → Backend) ────────────────────────────────
// The React dashboard calls this to approve or reject a staged order.
type GreenLightServiceClient interface {
	// Approve a staged order — triggers IBKR execution.
	Approve(ctx context.Context, in *GreenLightRequest, opts ...grpc.CallOption) (*GreenLightResponse, error)
	// Reject a staged order — marks it as rejected, no execution.
	Reject(ctx context.Context, in *GreenLightRequest, opts ...grpc.CallOption) (*GreenLightResponse, error)
	// List all pending staged orders.
	ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error)
}

type greenLightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreenLightServiceClient(cc grpc.ClientConnInterface) GreenLightServiceClient {
	return &greenLightServiceClient{cc}
}

func (c *greenLightServiceClient) Approve(ctx context.Context, in *GreenLightRequest, opts ...grpc.CallOption) (*GreenLightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenLightResponse)
	err := c.cc.Invoke(ctx, GreenLightService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenLightServiceClient) Reject(ctx context.Context, in *GreenLightRequest, opts ...grpc.CallOption) (*GreenLightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenLightResponse)
	err := c.cc.Invoke(ctx, GreenLightService_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenLightServiceClient) ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingResponse)
	err := c.cc.Invoke(ctx, GreenLightService_ListPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreenLightServiceServer is the server API for GreenLightService service.
// All implementations must embed UnimplementedGreenLightServiceServer
// for forward compatibility.
//
// ─── Green Light Service (Dashboard → Backend) ────────────────────────────────
// The React dashboard calls this to approve or reject a staged order.
type GreenLightServiceServer interface {
	// Approve a staged order — triggers IBKR execution.
	Approve(context.Context, *GreenLightRequest) (*GreenLightResponse, error)
	// Reject a staged order — marks it as rejected, no execution.
	Reject(context.Context, *GreenLightRequest) (*GreenLightResponse, error)
	// List all pending staged orders.
	ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error)
	mustEmbedUnimplementedGreenLightServiceServer()
}

// UnimplementedGreenLightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreenLightServiceServer struct{}

func (UnimplementedGreenLightServiceServer) Approve(context.Context, *GreenLightRequest) (*GreenLightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedGreenLightServiceServer) Reject(context.Context, *GreenLightRequest) (*GreenLightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedGreenLightServiceServer) ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPending not implemented")
}
func (UnimplementedGreenLightServiceServer) mustEmbedUnimplementedGreenLightServiceServer() {}
func (UnimplementedGreenLightServiceServer) testEmbeddedByValue()                           {}

// UnsafeGreenLightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreenLightServiceServer will
// result in compilation errors.
type UnsafeGreenLightServiceServer interface {
	mustEmbedUnimplementedGreenLightServiceServer()
}

func RegisterGreenLightServiceServer(s grpc.ServiceRegistrar, srv GreenLightServiceServer) {
	// If the following call panics, it indicates UnimplementedGreenLightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreenLightService_ServiceDesc, srv)
}

func _GreenLightService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreenLightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenLightServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenLightService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenLightServiceServer).Approve(ctx, req.(*GreenLightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenLightService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreenLightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenLightServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenLightService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenLightServiceServer).Reject(ctx, req.(*GreenLightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenLightService_ListPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenLightServiceServer).ListPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenLightService_ListPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenLightServiceServer).ListPending(ctx, req.(*ListPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreenLightService_ServiceDesc is the grpc.ServiceDesc for GreenLightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreenLightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketflow.GreenLightService",
	HandlerType: (*GreenLightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Approve",
			Handler:    _GreenLightService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _GreenLightService_Reject_Handler,
		},
		{
			MethodName: "ListPending",
			Handler:    _GreenLightService_ListPending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signals.proto",
}
