"""
signal_agent.py — Signal Generation Agent
==========================================
Generates candidate trading signals from market data using Ollama
(low complexity, runs locally). The signal is a structured proposal
that the debate agent and risk agent will then evaluate.
"""
from __future__ import annotations

import json
import re
import uuid
from typing import Any

import structlog
from pydantic import BaseModel, Field, field_validator

from .router import Complexity, LLMRouter

log = structlog.get_logger(__name__)


class CandidateSignal(BaseModel):
    """A candidate trading signal generated by the signal agent."""
    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    direction: str  # BUY | SELL | SHORT | COVER
    quantity: float
    limit_price: float = 0.0   # 0 = market order
    reasoning: str
    strategy_name: str
    initial_confidence: float  # 0.0–1.0

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: str) -> str:
        allowed = {"BUY", "SELL", "SHORT", "COVER"}
        if v.upper() not in allowed:
            raise ValueError(f"direction must be one of {allowed}")
        return v.upper()

    @field_validator("initial_confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("initial_confidence must be 0.0–1.0")
        return v


class SignalAgent:
    """
    Watches market data and generates candidate signals using Ollama.

    In production, wire this to a real-time data feed (e.g., IBKR market
    data stream, Polygon.io, or Alpha Vantage) and inject the live candles
    into the prompt. For the scaffold, we use a static market snapshot.
    """

    SYSTEM_PROMPT = """You are a quantitative trading signal generator. Output ONLY raw JSON — no markdown, no explanation.

== STRATEGY: DUAL_MOMENTUM (ONLY ACTIVE STRATEGY) ==
This is the ONLY valid strategy. Validated on 5 years of historical data. Sharpe 0.79, out-of-sample Sharpe 1.07.

Universe: QQQ, GLD, TLT, EEM, XLE ONLY.
If the symbol is NOT in this list → output null immediately.

Entry signal (BUY only — no SELL or SHORT):
  REQUIRED: close ≥ high_52w × 0.98 (within 2% of 52-week high)
  REQUIRED: close > sma_50 (confirmed uptrend)
  If either condition is false → output null.

Exit: handled by position monitor (SMA20 cross). Do NOT specify take_profit — set limit_price=0 always.

== CONFIDENCE CALIBRATION ==
Start at 0.75 (higher baseline — validated strategy with positive out-of-sample Sharpe).

Evidence (add to 0.75 baseline):
  close ≥ high_52w × 0.99 (at or near all-time highs): +0.08
  volume > 1.5x volume_sma20 (institutional participation): +0.06
  sma_50 trending up (close > sma_50, clear uptrend): +0.04
  VIX < 20 (risk-on macro environment): +0.03

Cap at 0.90. Output null if confidence < 0.75 after calibration.

== POSITION SIZING ==
Use ATR-based formula: dollar_risk = $1,000 (1% of $100k account).
stop_distance = atr_14 × 2.0
shares = int(dollar_risk / stop_distance)
Cap: min(shares, 20) — ETFs are expensive ($300-500/share), max 20 shares per position.

== NO-TRADE CONDITIONS (output the single word null — NOT a JSON object) ==
CRITICAL: When any condition below is true, output ONLY the word null with no JSON wrapper.
Do NOT output {"confidence": 0.0, ...} — that is wrong. Output: null

- Symbol NOT in [QQQ, GLD, TLT, EEM, XLE]
- close < sma_50
- close < high_52w × 0.98
- ATR% > 5.0%
- confidence < 0.75 after calibration

== INDICATOR INTERPRETATION (for reference only) ==

RSI (14-period) — DIRECTION MATTERS more than the level:
  Rising RSI (e.g. 27→33): momentum reversing upward — BUY signal
  Falling RSI (e.g. 33→27): momentum deteriorating — SELL/SHORT signal
  < 25: strongly oversold (mean_reversion BUY candidate)
  25–35: oversold, momentum entry if trend supports
  35–65: neutral — no edge, skip unless strong volume breakout
  65–75: overbought, momentum entry if trend supports
  > 75: strongly overbought (mean_reversion SELL candidate)

MACD (12/26/9):
  Histogram expanding positively: bullish momentum accelerating → momentum_breakout BUY
  Histogram expanding negatively: bearish momentum accelerating → momentum_breakout SHORT
  Histogram contracting: momentum fading → do NOT initiate momentum trades
  Zero-line crossover: strongest signal (trend change confirmation)
  Divergence from price: early reversal warning

Bollinger Bands (%B = (close - bb_lower) / (bb_upper - bb_lower)):
  %B < 0.05 + volume contracting: mean_reversion BUY
  %B > 0.95 + volume contracting: mean_reversion SELL
  %B 0.05–0.20 + volume expanding: momentum_breakout BUY from low base
  %B 0.80–0.95 + volume expanding: momentum_breakout SHORT from high base
  Narrow band width (squeeze): breakout imminent, wait for volume confirmation

ATR% (= atr_14 / close * 100):
  < 1.5%: low vol — mean_reversion preferred, full size
  1.5–3.0%: normal — all strategies, full size
  3.0–5.0%: elevated — reduce size 40%
  5.0–8.0%: high — reduce size 60%, momentum only with strong conviction
  > 8.0%: extreme — output null, no new entries

Volume (most independent indicator — highest weight):
  > 2.0x SMA20: very high conviction, institutional participation confirmed
  1.5–2.0x SMA20: high conviction, full position
  1.0–1.5x SMA20: moderate, reduce size 20%
  0.7–1.0x SMA20: weak — no breakout trades
  < 0.7x SMA20: no conviction — output null

== MARKET REGIME ==
VIX:
  < 15: risk-on — favour momentum BUY, full size
  15–20: normal — all strategies valid
  20–25: elevated — require 2+ independent confirmations, reduce size 20%
  25–30: risk-off — mean_reversion only, no new momentum BUYs, reduce size 40%
  > 30: fear spike — mean_reversion BUYs ARE VALID (contrarian, capitulation signal), NO momentum BUYs,
        NO new SHORTs (short squeeze risk), 50% size max
  NOTE: VIX > 30 is historically a mean-reversion BUY opportunity, NOT a blanket sell signal.

SPY trend:
  uptrend: favour BUY, SHORT only on extreme RSI/BB readings
  neutral: all strategies valid, require stronger confirmation
  downtrend: favour SELL/SHORT, BUY only on extreme mean_reversion with VIX > 28 (capitulation)

== POSITION SIZING — ATR-Based Risk Model (portfolio = $100,000) ==
Principle: size by how much you are willing to LOSE, not by how much you want to allocate.
This is the professional standard — position size is determined by volatility, not capital allocation.

Step 1 — Dollar risk per trade (VIX-adjusted):
  VIX < 15:    risk 1.25% of account = $1,250
  VIX 15–20:   risk 1.00% of account = $1,000
  VIX 20–25:   risk 0.75% of account = $750
  VIX 25–30:   risk 0.50% of account = $500
  VIX > 30:    risk 0.40% of account = $400

Step 2 — Stop distance (ATR × 2.0 multiplier):
  stop_distance = atr_14 × 2.0
  This is the distance from entry to stop-loss in dollars per share.

Step 3 — Share count:
  shares = int(dollar_risk / stop_distance)
  Cap: min(shares, 500, int(8000 / close))  ← never allocate more than 8% of account value

Example: close=$50, ATR=$1.50, VIX=17 → stop_distance=$3.00, dollar_risk=$1,000 → shares=333, capped at min(333, 500, 160) = 160

Output null if stop_distance < 0.01 (ATR too small to calculate meaningful stop).

== CONFIDENCE CALIBRATION ==
Start at 0.60. Add evidence — but respect correlation between RSI and MACD.

Independent evidence (full weight each):
  Volume > 1.5x SMA20 aligned with direction: +0.08
  SPY trend aligned with direction: +0.06
  VIX regime supports strategy type: +0.04
  ATR% appropriate for strategy (not extreme): +0.03

Correlated technical evidence (RSI + MACD together = +0.08 max, not additive):
  RSI direction AND MACD histogram both aligned: +0.08
  Bollinger %B extreme supporting signal (partially independent): +0.05

Cap at 0.90 — no model has > 90% edge on a 5-day directional call.
Output null if total confidence < 0.70 — below this, expected value is negative after costs.

== NO-TRADE CONDITIONS (output null immediately if any apply) ==
- ATR% > 8.0%
- Volume < 0.7x SMA20
- RSI 38–62 AND |MACD histogram| < 0.3 AND %B 0.30–0.70 (flat, no edge)
- Confidence < 0.70 after calibration
- momentum_breakout attempted when MACD histogram is contracting
- mean_reversion attempted when MACD histogram |value| > 1.0 (strong trend)
- Any BUY when SPY=downtrend AND VIX < 28 (no catching falling knives in bear market)
- momentum BUY when VIX > 25

Output ONLY raw JSON starting with { — no markdown, no explanation:
{"symbol":"NVDA","direction":"BUY","quantity":160,"limit_price":0,"reasoning":"RSI recovering 26→31 (upward, confirming reversal); %B at 0.06 (BB lower extreme); volume contracting to 0.85x avg (mean-reversion setup, not breakout); MACD histogram near zero, not directional. VIX 17 (normal), SPY uptrend. Three partially-independent signals align for mean_reversion BUY. RSI+MACD correlated so counted as single block (+0.08); volume contraction confirms overextension (+0.05); SPY tailwind (+0.06); VIX normal (+0.04) = 0.83 confidence. Sizing: VIX 17 → dollar_risk=$1,000; ATR=$3.12 → stop_distance=$6.24; shares=160 (capped at 8% allocation).","strategy_name":"mean_reversion","initial_confidence":0.83}"""

    def __init__(self, router: LLMRouter, strategy_name: str = "dual_momentum") -> None:
        self.router = router
        self.strategy_name = strategy_name

    def generate(self, market_snapshot: dict[str, Any]) -> CandidateSignal | None:
        """
        Generate a candidate signal from a market data snapshot.

        Args:
            market_snapshot: Dict with keys like 'symbol', 'ohlcv', 'indicators', etc.

        Returns:
            A CandidateSignal, or None if the model output was invalid.
        """
        symbol = market_snapshot.get("symbol", "UNKNOWN")
        log.info("signal_agent.generate", symbol=symbol, strategy=self.strategy_name)

        indicators = market_snapshot.get("indicators", {})
        ohlcv      = market_snapshot.get("ohlcv", {})
        ctx        = market_snapshot.get("market_context", {})
        close      = ohlcv.get("close", 0)
        atr        = indicators.get("atr_14", 0)
        vix        = ctx.get("vix", 18)
        stop_dist  = round(atr * 2.0, 4)

        sizing_hint = (
            f"\nSIZING INPUTS (use ATR-based formula from system prompt):\n"
            f"  close=${close}, atr_14=${atr}, stop_distance=${stop_dist} (atr×2.0), vix={vix}\n"
        )

        user_prompt = (
            f"Analyze this market data and output a trading signal JSON.\n\n"
            f"MARKET DATA:\n{json.dumps(market_snapshot, indent=2)}\n"
            f"{sizing_hint}\n"
            f"OUTPUT a JSON object with exactly these keys: "
            f"symbol, direction (BUY/SELL/SHORT/COVER), quantity (integer shares, use ATR sizing), "
            f"limit_price (0 for market), reasoning (string, include sizing calc), "
            f"strategy_name, initial_confidence (0.0-1.0)"
        )

        raw = ""
        try:
            raw = self.router.complete(
                system=self.SYSTEM_PROMPT,
                user=user_prompt,
                complexity=Complexity.LOW,
                max_tokens=1200,  # increased — dual_momentum reasoning can be verbose
                schema=CandidateSignal,
            )
            # Extract first JSON object if model added surrounding text
            json_str = raw
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                json_str = match.group(0)
            data = json.loads(json_str)
            if not isinstance(data, dict):
                log.info("signal_agent.no_trade", symbol=symbol, reason="model returned null")
                return None
            # Reject confidence=0.0 — model didn't calibrate, treat as no-trade
            if float(data.get("initial_confidence", 0)) == 0.0:
                log.info("signal_agent.no_trade", symbol=symbol, reason="confidence=0.0 (model did not calibrate)")
                return None
            # The configured strategy stamps the label — never trust the LLM's
            # free-text strategy_name (live positions got labeled "momentum" /
            # "mean_reversion" on dual_momentum trades, dodging the trend exit).
            data["strategy_name"] = self.strategy_name
            signal = CandidateSignal(**data)
            log.info(
                "signal_agent.generated",
                symbol=signal.symbol,
                direction=signal.direction,
                confidence=signal.initial_confidence,
            )
            return signal

        except (json.JSONDecodeError, ValueError) as exc:
            log.error("signal_agent.parse_error", error=str(exc), raw=raw[:200])
            return None
