"""
signal_agent.py — Signal Generation Agent
==========================================
Generates candidate trading signals from market data using Ollama
(low complexity, runs locally). The signal is a structured proposal
that the debate agent and risk agent will then evaluate.
"""
from __future__ import annotations

import json
import uuid
from typing import Any

import structlog
from pydantic import BaseModel, Field, field_validator

from .router import Complexity, LLMRouter

log = structlog.get_logger(__name__)


class CandidateSignal(BaseModel):
    """A candidate trading signal generated by the signal agent."""
    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    direction: str  # BUY | SELL | SHORT | COVER
    quantity: float
    limit_price: float = 0.0   # 0 = market order
    reasoning: str
    strategy_name: str
    initial_confidence: float  # 0.0–1.0

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: str) -> str:
        allowed = {"BUY", "SELL", "SHORT", "COVER"}
        if v.upper() not in allowed:
            raise ValueError(f"direction must be one of {allowed}")
        return v.upper()

    @field_validator("initial_confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("initial_confidence must be 0.0–1.0")
        return v


class SignalAgent:
    """
    Watches market data and generates candidate signals using Ollama.

    In production, wire this to a real-time data feed (e.g., IBKR market
    data stream, Polygon.io, or Alpha Vantage) and inject the live candles
    into the prompt. For the scaffold, we use a static market snapshot.
    """

    SYSTEM_PROMPT = """You are a quantitative trading signal generator.
Given a market data snapshot, produce a single actionable trading signal.
Respond with ONLY a valid JSON object matching this schema:
{
  "symbol": "string (ticker symbol)",
  "direction": "BUY | SELL | SHORT | COVER",
  "quantity": number,
  "limit_price": number (0 for market order),
  "reasoning": "string (concise, 2-3 sentences)",
  "strategy_name": "string (name of the alpha strategy used)",
  "initial_confidence": number (0.0-1.0)
}
Do not include any text outside the JSON object."""

    def __init__(self, router: LLMRouter, strategy_name: str = "momentum_breakout") -> None:
        self.router = router
        self.strategy_name = strategy_name

    def generate(self, market_snapshot: dict[str, Any]) -> CandidateSignal | None:
        """
        Generate a candidate signal from a market data snapshot.

        Args:
            market_snapshot: Dict with keys like 'symbol', 'ohlcv', 'indicators', etc.

        Returns:
            A CandidateSignal, or None if the model output was invalid.
        """
        symbol = market_snapshot.get("symbol", "UNKNOWN")
        log.info("signal_agent.generate", symbol=symbol, strategy=self.strategy_name)

        user_prompt = (
            f"Market data snapshot:\n{json.dumps(market_snapshot, indent=2)}\n\n"
            f"Strategy context: {self.strategy_name}\n"
            "Generate a trading signal."
        )

        try:
            raw = self.router.complete(
                system=self.SYSTEM_PROMPT,
                user=user_prompt,
                complexity=Complexity.LOW,  # Ollama handles this
            )
            data = json.loads(raw)
            data.setdefault("strategy_name", self.strategy_name)
            signal = CandidateSignal(**data)
            log.info(
                "signal_agent.generated",
                symbol=signal.symbol,
                direction=signal.direction,
                confidence=signal.initial_confidence,
            )
            return signal

        except (json.JSONDecodeError, ValueError) as exc:
            log.error("signal_agent.parse_error", error=str(exc), raw=raw[:200])
            return None
