"""
signal_agent.py — Signal Generation Agent
==========================================
Generates candidate trading signals from market data using Ollama
(low complexity, runs locally). The signal is a structured proposal
that the debate agent and risk agent will then evaluate.
"""
from __future__ import annotations

import json
import re
import uuid
from typing import Any

import structlog
from pydantic import BaseModel, Field, field_validator

from .router import Complexity, LLMRouter

log = structlog.get_logger(__name__)


class CandidateSignal(BaseModel):
    """A candidate trading signal generated by the signal agent."""
    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    direction: str  # BUY | SELL | SHORT | COVER
    quantity: float
    limit_price: float = 0.0   # 0 = market order
    reasoning: str
    strategy_name: str
    initial_confidence: float  # 0.0–1.0

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: str) -> str:
        allowed = {"BUY", "SELL", "SHORT", "COVER"}
        if v.upper() not in allowed:
            raise ValueError(f"direction must be one of {allowed}")
        return v.upper()

    @field_validator("initial_confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("initial_confidence must be 0.0–1.0")
        return v


class SignalAgent:
    """
    Watches market data and generates candidate signals using Ollama.

    In production, wire this to a real-time data feed (e.g., IBKR market
    data stream, Polygon.io, or Alpha Vantage) and inject the live candles
    into the prompt. For the scaffold, we use a static market snapshot.
    """

    SYSTEM_PROMPT = """You are a quantitative trading signal generator. Output ONLY raw JSON, no explanation.

Example output:
{"symbol":"AAPL","direction":"BUY","quantity":100,"limit_price":0,"reasoning":"RSI oversold with volume breakout.","strategy_name":"momentum_breakout","initial_confidence":0.85}

Rules:
- direction must be one of: BUY, SELL, SHORT, COVER
- quantity is number of shares (integer)
- limit_price is 0 for market order
- initial_confidence is 0.0 to 1.0
- Output starts with { and ends with }
- No markdown, no explanation, no text outside the JSON"""

    def __init__(self, router: LLMRouter, strategy_name: str = "momentum_breakout") -> None:
        self.router = router
        self.strategy_name = strategy_name

    def generate(self, market_snapshot: dict[str, Any]) -> CandidateSignal | None:
        """
        Generate a candidate signal from a market data snapshot.

        Args:
            market_snapshot: Dict with keys like 'symbol', 'ohlcv', 'indicators', etc.

        Returns:
            A CandidateSignal, or None if the model output was invalid.
        """
        symbol = market_snapshot.get("symbol", "UNKNOWN")
        log.info("signal_agent.generate", symbol=symbol, strategy=self.strategy_name)

        user_prompt = (
            f"Analyze this market data and output a trading signal JSON.\n\n"
            f"MARKET DATA:\n{json.dumps(market_snapshot, indent=2)}\n\n"
            f"OUTPUT a JSON object with exactly these keys: "
            f"symbol, direction (BUY/SELL/SHORT/COVER), quantity (integer shares), "
            f"limit_price (0 for market), reasoning (string), strategy_name, initial_confidence (0.0-1.0)"
        )

        raw = ""
        try:
            raw = self.router.complete(
                system=self.SYSTEM_PROMPT,
                user=user_prompt,
                complexity=Complexity.LOW,  # Ollama handles this
                schema=CandidateSignal,
            )
            # Extract first JSON object if model added surrounding text
            json_str = raw
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                json_str = match.group(0)
            data = json.loads(json_str)
            data.setdefault("strategy_name", self.strategy_name)
            signal = CandidateSignal(**data)
            log.info(
                "signal_agent.generated",
                symbol=signal.symbol,
                direction=signal.direction,
                confidence=signal.initial_confidence,
            )
            return signal

        except (json.JSONDecodeError, ValueError) as exc:
            log.error("signal_agent.parse_error", error=str(exc), raw=raw[:200])
            return None
